apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-fmhb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-fmhb
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-fmhb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-fmhb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-fmhb
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-fwfk-tenant/rhtap-demo-app/hacbs-test-project-fmhb@sha256:73a4b9749d91cce67d74ddce31e83d7a154c55715c8ffe44678818eb11d77d9d
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
